- id: index
  title: Python - grunder
  link_text: Grunder
  md_file: index.md
  html_file: index.html

- id: fortsattning
  title: Python - fortsättning
  link_text: Fortsättning
  md_file: fortsattning.md
  html_file: fortsattning.html

- id: tillampningar
  title: Tillämpningar
  link_text: Tillämpningar
  md_file: uc.md
  html_file: tillampningar.html

- id: verktyg
  title: Utvecklingsmiljö och verktyg
  link_text: Utvecklingsmiljö och verktyg
  md_file: verktyg.md
  html_file: utveckling.html
